// AUTO-GENERATED by scripts/gen-font-metrics.ts — do not edit by hand.
import type { FamilyMetrics } from "./types";

/** Weights each family actually ships. Requesting anything else means faux bold. */
export const AVAILABLE_WEIGHTS: Record<string, number[]> = {
  "Space Grotesk": [400, 500, 600, 700],
  "Space Mono": [400, 700],
  "Archivo Black": [400],
  "Bebas Neue": [400],
  "DM Serif Display": [400],
  "Instrument Serif": [400],
  "Playfair Display": [400, 500, 600, 700, 800, 900],
  Sora: [400, 500, 600, 700, 800],
  Syne: [400, 500, 600, 700, 800],
  Fraunces: [400, 500, 600, 700, 800, 900],
  "JetBrains Mono": [400, 500, 600, 700, 800],
  "IBM Plex Mono": [400, 500, 600, 700],
  Inter: [400, 500, 600, 700, 800, 900],
  "DM Mono": [400, 500],
  Manrope: [400, 500, 600, 700, 800],
  "Work Sans": [400, 500, 600, 700, 800, 900],
  "Fira Sans": [400, 500, 600, 700, 800, 900],
};

export const METRIC_LOADERS: Record<string, () => Promise<FamilyMetrics>> = {
  "Space Grotesk": () =>
    import("./space-grotesk.json").then((m) => m.default as unknown as FamilyMetrics),
  "Space Mono": () =>
    import("./space-mono.json").then((m) => m.default as unknown as FamilyMetrics),
  "Archivo Black": () =>
    import("./archivo-black.json").then((m) => m.default as unknown as FamilyMetrics),
  "Bebas Neue": () =>
    import("./bebas-neue.json").then((m) => m.default as unknown as FamilyMetrics),
  "DM Serif Display": () =>
    import("./dm-serif-display.json").then((m) => m.default as unknown as FamilyMetrics),
  "Instrument Serif": () =>
    import("./instrument-serif.json").then((m) => m.default as unknown as FamilyMetrics),
  "Playfair Display": () =>
    import("./playfair-display.json").then((m) => m.default as unknown as FamilyMetrics),
  Sora: () => import("./sora.json").then((m) => m.default as unknown as FamilyMetrics),
  Syne: () => import("./syne.json").then((m) => m.default as unknown as FamilyMetrics),
  Fraunces: () => import("./fraunces.json").then((m) => m.default as unknown as FamilyMetrics),
  "JetBrains Mono": () =>
    import("./jetbrains-mono.json").then((m) => m.default as unknown as FamilyMetrics),
  "IBM Plex Mono": () =>
    import("./ibm-plex-mono.json").then((m) => m.default as unknown as FamilyMetrics),
  Inter: () => import("./inter.json").then((m) => m.default as unknown as FamilyMetrics),
  "DM Mono": () => import("./dm-mono.json").then((m) => m.default as unknown as FamilyMetrics),
  Manrope: () => import("./manrope.json").then((m) => m.default as unknown as FamilyMetrics),
  "Work Sans": () => import("./work-sans.json").then((m) => m.default as unknown as FamilyMetrics),
  "Fira Sans": () => import("./fira-sans.json").then((m) => m.default as unknown as FamilyMetrics),
};
