// The badge that has always been hardcoded in badge-render.ts, expressed as a
// BadgeDoc. Every constant here is transcribed from that file, so the engine
// can be checked against it operation by operation.
//
// Node ids are the names that will show up as Figma layers, so they are written
// for a human reading the layer panel, not for the code.

import { CURRENT_DOC_VERSION, type BadgeDoc, type BadgeNode } from "../schema";

const W = 1080;
const H = 1600;
const MARGIN = 26;
const INNER_PAD = 66;

/** badge-render.ts: innerX = MARGIN + INNER_PAD * 0.34 ≈ 48.44 */
const INNER_X = MARGIN + INNER_PAD * 0.34;
const INNER_W = W - INNER_X * 2;

const SEAL_SIZE = 148;
const SEAL_MARGIN = 24;
const QR_SIZE = 156;
const QR_PAD = 8;
const PHOTO_MAX = 680;
const PHOTO_MIN = 380;

/** Header sits MARGIN + 44 from the top; the stack starts there. */
const HEADER_TOP = MARGIN + 44;

const CORNER_LEN = 36;
const CORNER_THICK = 5;

/**
 * The eight bars that make the four corner brackets around the photo, anchored
 * to its box so they follow it when it shrinks. Offsets reproduce the ±3 bleed
 * the renderer applies, including the bottom pair sitting CORNER_LEN-3 above
 * the lower edge rather than on it.
 */
function cornerBrackets(): BadgeNode[] {
  const bar = (
    id: string,
    anchor: "tl" | "tr" | "bl" | "br",
    dx: number,
    dy: number,
    w: number,
    h: number,
  ): BadgeNode => ({
    type: "rect",
    id,
    name: id.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()),
    position: { mode: "absolute", anchor, dx, dy },
    width: w,
    height: h,
    fill: "$accent",
    radius: 0,
    grow: 0,
    shrink: 0,
    alignSelf: "auto",
    opacity: 1,
    snap: false,
  });
  const bottomBarDy = CORNER_THICK - CORNER_LEN + 3;
  return [
    bar("corner-tl-h", "tl", -3, -3, CORNER_LEN, CORNER_THICK),
    bar("corner-tl-v", "tl", -3, -3, CORNER_THICK, CORNER_LEN),
    bar("corner-tr-h", "tr", 3, -3, CORNER_LEN, CORNER_THICK),
    bar("corner-tr-v", "tr", 3, -3, CORNER_THICK, CORNER_LEN),
    bar("corner-bl-h", "bl", -3, bottomBarDy, CORNER_LEN, CORNER_THICK),
    bar("corner-bl-v", "bl", -3, 3, CORNER_THICK, CORNER_LEN),
    bar("corner-br-h", "br", 3, bottomBarDy, CORNER_LEN, CORNER_THICK),
    bar("corner-br-v", "br", 3, 3, CORNER_THICK, CORNER_LEN),
  ];
}

export const CLASSIC_BADGE_DOC: BadgeDoc = {
  version: CURRENT_DOC_VERSION,
  meta: { name: "Classic", origin: "system" },
  canvas: { width: W, height: H, background: "$palette.bg" },
  vars: {},
  root: {
    type: "stack",
    id: "badge",
    name: "Badge",
    width: W,
    height: H,
    gap: 0,
    align: "start",
    justify: "start",
    grow: 0,
    shrink: 0,
    alignSelf: "auto",
    opacity: 1,
    snap: false,
    radius: 0,
    clip: "none",
    children: [
      // ---- frame: two nested rectangles, drawn over the paper ----
      {
        type: "rect",
        id: "frame-outer",
        name: "Frame Outer",
        position: { mode: "absolute", anchor: "tl", dx: MARGIN, dy: MARGIN },
        width: W - MARGIN * 2,
        height: H - MARGIN * 2,
        stroke: { color: "$accent", width: 3, inset: 0 },
        radius: 0,
        grow: 0,
        shrink: 0,
        alignSelf: "auto",
        opacity: 1,
        snap: false,
      },
      {
        type: "rect",
        id: "frame-inner",
        name: "Frame Inner",
        position: { mode: "absolute", anchor: "tl", dx: MARGIN + 10, dy: MARGIN + 10 },
        width: W - (MARGIN + 10) * 2,
        height: H - (MARGIN + 10) * 2,
        stroke: { color: "$palette.text|alpha($derived.hairlineAlpha)", width: 1, inset: 0 },
        radius: 0,
        grow: 0,
        shrink: 0,
        alignSelf: "auto",
        opacity: 1,
        snap: false,
      },

      // ---- content column ----
      {
        type: "stack",
        id: "content",
        name: "Content",
        position: { mode: "absolute", anchor: "tl", dx: INNER_X, dy: HEADER_TOP },
        width: INNER_W,
        height: H - HEADER_TOP - MARGIN - INNER_PAD * 0.5,
        gap: 0,
        align: "start",
        justify: "start",
        grow: 0,
        shrink: 0,
        alignSelf: "auto",
        opacity: 1,
        snap: false,
        radius: 0,
        clip: "none",
        children: [
          {
            type: "row",
            id: "header",
            name: "Header",
            width: "fill",
            gap: SEAL_MARGIN,
            align: "start",
            justify: "start",
            grow: 0,
            shrink: 0,
            alignSelf: "auto",
            opacity: 1,
            snap: false,
            radius: 0,
            clip: "none",
            children: [
              {
                type: "stack",
                id: "header-text",
                name: "Header Text",
                grow: 1,
                shrink: 0,
                alignSelf: "auto",
                gap: 0,
                align: "start",
                justify: "start",
                opacity: 1,
                snap: false,
                radius: 0,
                clip: "none",
                children: [
                  {
                    type: "text",
                    id: "kicker",
                    name: "Kicker",
                    text: "· WHAT'S BREWING?",
                    font: "body",
                    weight: 700,
                    size: 20,
                    height: 22,
                    lineHeight: 1.08,
                    tracking: 0,
                    color: "$accent",
                    align: "left",
                    transform: "none",
                    grow: 0,
                    shrink: 0,
                    alignSelf: "auto",
                    opacity: 1,
                    snap: false,
                    margin: [0, 0, 14, 0],
                  },
                  {
                    type: "text",
                    id: "headline",
                    name: "Headline",
                    text: "$event.name",
                    font: "heading",
                    weight: 900,
                    size: 88,
                    fit: { mode: "shrinkWrap", from: 88, to: 40, step: 2, maxLines: 2 },
                    lineHeight: 1.08,
                    tracking: 0,
                    color: "$palette.text",
                    align: "left",
                    transform: "upper",
                    grow: 0,
                    shrink: 0,
                    alignSelf: "auto",
                    opacity: 1,
                    snap: false,
                    margin: [0, 0, 14, 0],
                  },
                  {
                    type: "row",
                    id: "meta",
                    name: "Meta",
                    width: "fill",
                    height: 22,
                    gap: 32,
                    align: "start",
                    justify: "between",
                    grow: 0,
                    shrink: 0,
                    alignSelf: "auto",
                    opacity: 1,
                    snap: false,
                    radius: 0,
                    clip: "none",
                    children: [
                      {
                        type: "text",
                        id: "city",
                        name: "City",
                        text: "$event.subtitle",
                        font: "body",
                        weight: 700,
                        size: 22,
                        width: "auto",
                        lineHeight: 1.08,
                        tracking: 0,
                        color: "$accent",
                        align: "left",
                        transform: "upper",
                        grow: 0,
                        shrink: 0,
                        alignSelf: "auto",
                        opacity: 1,
                        snap: false,
                      },
                      {
                        type: "text",
                        id: "date",
                        name: "Date",
                        text: "$event.dateLine",
                        font: "body",
                        weight: 400,
                        size: 22,
                        width: "auto",
                        lineHeight: 1.08,
                        tracking: 0,
                        color: "$palette.text|alpha(0.7)",
                        align: "right",
                        transform: "none",
                        grow: 0,
                        shrink: 0,
                        alignSelf: "auto",
                        opacity: 1,
                        snap: false,
                      },
                    ],
                  },
                ],
              },
              {
                type: "image",
                id: "seal",
                name: "Seal",
                src: "$event.coverUrl",
                visibleIf: "$event.coverUrl",
                width: SEAL_SIZE,
                height: SEAL_SIZE,
                fit: "cover",
                shape: "circle",
                stroke: { color: "$palette.text", width: 5, inset: 0 },
                // In flow, so the header text column narrows by exactly the seal
                // plus the gap when a cover exists — and reclaims it when it does
                // not. The margins also carry the SEAL_SIZE + 8 floor the header
                // only has while a cover is present.
                margin: [-4, 0, 12, 0],
                grow: 0,
                shrink: 0,
                alignSelf: "auto",
                opacity: 1,
                snap: false,
              },
            ],
          },

          {
            // Wrapper so the corner brackets can anchor to the photo box while
            // it shrinks. The photo is the only node that gives up space.
            type: "stack",
            id: "photo",
            name: "Photo",
            width: PHOTO_MAX,
            aspect: 1,
            minHeight: PHOTO_MIN,
            maxHeight: PHOTO_MAX,
            margin: [40, 0, 22, 0],
            gap: 0,
            align: "start",
            justify: "start",
            grow: 0,
            shrink: 1,
            alignSelf: "center",
            opacity: 1,
            snap: true,
            radius: 0,
            clip: "none",
            children: [
              {
                type: "image",
                id: "photo-image",
                name: "Photo Image",
                src: "$photo",
                width: "fill",
                aspect: 1,
                fit: "contain",
                backdrop: "$palette.surface",
                shape: "rect",
                stroke: { color: "$accent|alpha($derived.photoStrokeAlpha)", width: 2, inset: 0 },
                grow: 0,
                shrink: 0,
                alignSelf: "auto",
                opacity: 1,
                snap: false,
              },
              ...cornerBrackets(),
            ],
          },

          {
            type: "text",
            id: "caption",
            name: "Caption",
            text: "$event.dateLine|prefix(· )|suffix( ·)",
            font: "body",
            weight: 400,
            size: 18,
            height: 22,
            width: "fill",
            lineHeight: 1.08,
            tracking: 0,
            color: "$palette.text|alpha(0.5)",
            align: "center",
            transform: "none",
            margin: [0, 0, 40, 0],
            grow: 0,
            shrink: 0,
            alignSelf: "auto",
            opacity: 1,
            snap: false,
          },

          {
            type: "text",
            id: "name",
            name: "Name",
            text: "$user.firstName",
            font: "heading",
            weight: 900,
            size: 104,
            fit: { mode: "shrinkWrap", from: 104, to: 42, step: 2, maxLines: 2 },
            lineHeight: 1.08,
            tracking: 0,
            color: "$palette.text",
            align: "left",
            transform: "upper",
            margin: [0, 0, 12, 0],
            grow: 0,
            shrink: 0,
            alignSelf: "auto",
            opacity: 1,
            snap: false,
          },

          {
            type: "text",
            id: "role",
            name: "Role",
            text: "$user.role|upper|prefix(→ )",
            font: "body",
            weight: 700,
            size: 26,
            fit: { mode: "shrink", from: 26, to: 16, step: 2, maxLines: 1 },
            lineHeight: 1,
            tracking: 0,
            color: "$accent",
            align: "left",
            transform: "none",
            margin: [0, 0, 18, 0],
            grow: 0,
            shrink: 0,
            alignSelf: "auto",
            opacity: 1,
            snap: false,
          },

          {
            type: "row",
            id: "divider",
            name: "Divider",
            width: "fill",
            height: 3,
            // 208 - 200: the rule starts 8px after the accent bar.
            gap: 8,
            align: "start",
            justify: "start",
            margin: [0, 0, 32, 0],
            grow: 0,
            shrink: 0,
            alignSelf: "auto",
            opacity: 1,
            snap: false,
            radius: 0,
            clip: "none",
            children: [
              {
                type: "rect",
                id: "divider-bar",
                name: "Divider Bar",
                width: 200,
                height: 3,
                fill: "$accent",
                radius: 0,
                grow: 0,
                shrink: 0,
                alignSelf: "auto",
                opacity: 1,
                snap: false,
              },
              {
                type: "rect",
                id: "divider-rule",
                name: "Divider Rule",
                width: INNER_W - 208,
                height: 1,
                fill: "$palette.text|alpha(0.16)",
                margin: [1, 0, 0, 0],
                radius: 0,
                grow: 0,
                shrink: 0,
                alignSelf: "auto",
                opacity: 1,
                snap: false,
              },
            ],
          },

          {
            type: "row",
            id: "scan",
            name: "Scan Block",
            width: "fill",
            height: QR_SIZE + QR_PAD * 2,
            gap: 24,
            align: "start",
            justify: "between",
            grow: 0,
            shrink: 0,
            alignSelf: "auto",
            opacity: 1,
            snap: false,
            radius: 0,
            clip: "none",
            children: [
              {
                type: "stack",
                id: "scan-text",
                name: "Scan Text",
                grow: 1,
                shrink: 0,
                alignSelf: "auto",
                gap: 0,
                align: "start",
                justify: "start",
                opacity: 1,
                snap: false,
                radius: 0,
                clip: "none",
                children: [
                  {
                    type: "text",
                    id: "scan-label",
                    name: "Scan Label",
                    text: "SCAN →",
                    font: "body",
                    weight: 700,
                    size: 16,
                    height: 26,
                    margin: [4, 0, 0, 0],
                    lineHeight: 1.08,
                    tracking: 0,
                    color: "$palette.text",
                    align: "left",
                    transform: "none",
                    grow: 0,
                    shrink: 0,
                    alignSelf: "auto",
                    opacity: 1,
                    snap: false,
                  },
                  {
                    type: "text",
                    id: "scan-hint",
                    name: "Scan Hint",
                    text: "REGISTER FOR THIS EVENT",
                    font: "body",
                    weight: 400,
                    size: 14,
                    height: 32,
                    lineHeight: 1.08,
                    tracking: 0,
                    color: "$palette.text|alpha(0.55)",
                    align: "left",
                    transform: "none",
                    grow: 0,
                    shrink: 0,
                    alignSelf: "auto",
                    opacity: 1,
                    snap: false,
                  },
                  {
                    type: "text",
                    id: "scan-url",
                    name: "Scan Url",
                    text: "$event.url|displayUrl",
                    font: "body",
                    weight: 700,
                    size: 20,
                    fit: { mode: "shrinkWrap", from: 20, to: 12, step: 2, maxLines: 2 },
                    lineHeight: 1.08,
                    tracking: 0,
                    color: "$palette.text",
                    align: "left",
                    transform: "none",
                    grow: 0,
                    shrink: 0,
                    alignSelf: "auto",
                    opacity: 1,
                    snap: false,
                  },
                ],
              },
              {
                // The QR is what aligns to the right edge; its padded plate
                // bleeds 8px outside the column, as the renderer draws it.
                type: "stack",
                id: "qr-frame",
                name: "QR Frame",
                width: QR_SIZE,
                height: QR_SIZE,
                gap: 0,
                align: "start",
                justify: "start",
                grow: 0,
                shrink: 0,
                alignSelf: "auto",
                opacity: 1,
                snap: false,
                radius: 0,
                clip: "none",
                children: [
                  {
                    type: "rect",
                    id: "qr-plate",
                    name: "QR Plate",
                    position: { mode: "absolute", anchor: "tl", dx: -QR_PAD, dy: -QR_PAD },
                    width: QR_SIZE + QR_PAD * 2,
                    height: QR_SIZE + QR_PAD * 2,
                    fill: "$palette.surface",
                    stroke: { color: "$palette.text|alpha(0.2)", width: 1, inset: 0 },
                    radius: 0,
                    grow: 0,
                    shrink: 0,
                    alignSelf: "auto",
                    opacity: 1,
                    snap: false,
                  },
                  {
                    type: "qr",
                    id: "qr",
                    name: "QR Code",
                    value: "$event.url",
                    ecc: "M",
                    quietZone: 2,
                    width: QR_SIZE,
                    height: QR_SIZE,
                    dark: "$palette.text",
                    light: "$palette.surface",
                    grow: 0,
                    shrink: 0,
                    alignSelf: "auto",
                    opacity: 1,
                    snap: false,
                  },
                ],
              },
            ],
          },
          {
            // The footer is painted pinned to the bottom, but the renderer still
            // subtracts its height and gap when deciding how big the photo can
            // be. Reserving it here keeps that budget identical.
            type: "spacer",
            id: "footer-space",
            name: "Footer Space",
            height: 22,
            margin: [24, 0, 0, 0],
            grow: 0,
            shrink: 0,
            alignSelf: "auto",
            opacity: 1,
            snap: false,
          },
        ],
      },

      // Pinned to the bottom, like max(scanBottom, H - MARGIN - 40) did.
      {
        type: "text",
        id: "footer",
        name: "Footer",
        text: "$event.name|lower|suffix( · powered by luma_)",
        font: "body",
        weight: 400,
        size: 18,
        fit: { mode: "shrink", from: 18, to: 12, step: 2, maxLines: 1 },
        position: { mode: "absolute", anchor: "tl", dx: INNER_X, dy: H - MARGIN - 40 },
        width: INNER_W,
        lineHeight: 1.08,
        tracking: 0,
        color: "$palette.text|alpha(0.4)",
        align: "center",
        transform: "none",
        grow: 0,
        shrink: 0,
        alignSelf: "auto",
        opacity: 1,
        snap: false,
      },
    ],
  },
};
