/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Phase2RouteImport } from './routes/phase-2'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatBadgeRouteImport } from './routes/api/chat-badge'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedImportRouteImport } from './routes/_authenticated/import'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1EventsRouteImport } from './routes/api/v1/events'
import { Route as ApiV1CalendarsRouteImport } from './routes/api/v1/calendars'
import { Route as ApiPublicImageRouteImport } from './routes/api/public/image'
import { Route as AuthenticatedEEventIdRouteImport } from './routes/_authenticated/e.$eventId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiV1EventsChangesRouteImport } from './routes/api/v1/events/changes'
import { Route as ApiV1EventsCanonicalIdRouteImport } from './routes/api/v1/events/$canonicalId'

const Phase2Route = Phase2RouteImport.update({
  id: '/phase-2',
  path: '/phase-2',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatBadgeRoute = ApiChatBadgeRouteImport.update({
  id: '/api/chat-badge',
  path: '/api/chat-badge',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportRoute = AuthenticatedImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventsRoute = ApiV1EventsRouteImport.update({
  id: '/api/v1/events',
  path: '/api/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CalendarsRoute = ApiV1CalendarsRouteImport.update({
  id: '/api/v1/calendars',
  path: '/api/v1/calendars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageRoute = ApiPublicImageRouteImport.update({
  id: '/api/public/image',
  path: '/api/public/image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEEventIdRoute = AuthenticatedEEventIdRouteImport.update({
  id: '/e/$eventId',
  path: '/e/$eventId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventsChangesRoute = ApiV1EventsChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => ApiV1EventsRoute,
} as any)
const ApiV1EventsCanonicalIdRoute = ApiV1EventsCanonicalIdRouteImport.update({
  id: '/$canonicalId',
  path: '/$canonicalId',
  getParentRoute: () => ApiV1EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/phase-2': typeof Phase2Route
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/events': typeof AuthenticatedEventsRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/import': typeof AuthenticatedImportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/api/chat-badge': typeof ApiChatBadgeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/e/$eventId': typeof AuthenticatedEEventIdRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/v1/calendars': typeof ApiV1CalendarsRoute
  '/api/v1/events': typeof ApiV1EventsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/events/$canonicalId': typeof ApiV1EventsCanonicalIdRoute
  '/api/v1/events/changes': typeof ApiV1EventsChangesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/phase-2': typeof Phase2Route
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/events': typeof AuthenticatedEventsRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/import': typeof AuthenticatedImportRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/api/chat-badge': typeof ApiChatBadgeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/e/$eventId': typeof AuthenticatedEEventIdRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/v1/calendars': typeof ApiV1CalendarsRoute
  '/api/v1/events': typeof ApiV1EventsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/events/$canonicalId': typeof ApiV1EventsCanonicalIdRoute
  '/api/v1/events/changes': typeof ApiV1EventsChangesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/phase-2': typeof Phase2Route
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/import': typeof AuthenticatedImportRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/api/chat-badge': typeof ApiChatBadgeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/e/$eventId': typeof AuthenticatedEEventIdRoute
  '/api/public/image': typeof ApiPublicImageRoute
  '/api/v1/calendars': typeof ApiV1CalendarsRoute
  '/api/v1/events': typeof ApiV1EventsRouteWithChildren
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/events/$canonicalId': typeof ApiV1EventsCanonicalIdRoute
  '/api/v1/events/changes': typeof ApiV1EventsChangesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/phase-2'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/events'
    | '/gallery'
    | '/import'
    | '/settings'
    | '/templates'
    | '/api/chat-badge'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/e/$eventId'
    | '/api/public/image'
    | '/api/v1/calendars'
    | '/api/v1/events'
    | '/api/v1/health'
    | '/api/v1/events/$canonicalId'
    | '/api/v1/events/changes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/phase-2'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/events'
    | '/gallery'
    | '/import'
    | '/settings'
    | '/templates'
    | '/api/chat-badge'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/e/$eventId'
    | '/api/public/image'
    | '/api/v1/calendars'
    | '/api/v1/events'
    | '/api/v1/health'
    | '/api/v1/events/$canonicalId'
    | '/api/v1/events/changes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/phase-2'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/events'
    | '/_authenticated/gallery'
    | '/_authenticated/import'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/api/chat-badge'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/e/$eventId'
    | '/api/public/image'
    | '/api/v1/calendars'
    | '/api/v1/events'
    | '/api/v1/health'
    | '/api/v1/events/$canonicalId'
    | '/api/v1/events/changes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  Phase2Route: typeof Phase2Route
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatBadgeRoute: typeof ApiChatBadgeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicImageRoute: typeof ApiPublicImageRoute
  ApiV1CalendarsRoute: typeof ApiV1CalendarsRoute
  ApiV1EventsRoute: typeof ApiV1EventsRouteWithChildren
  ApiV1HealthRoute: typeof ApiV1HealthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/phase-2': {
      id: '/phase-2'
      path: '/phase-2'
      fullPath: '/phase-2'
      preLoaderRoute: typeof Phase2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-badge': {
      id: '/api/chat-badge'
      path: '/api/chat-badge'
      fullPath: '/api/chat-badge'
      preLoaderRoute: typeof ApiChatBadgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import': {
      id: '/_authenticated/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AuthenticatedImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/events': {
      id: '/api/v1/events'
      path: '/api/v1/events'
      fullPath: '/api/v1/events'
      preLoaderRoute: typeof ApiV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/calendars': {
      id: '/api/v1/calendars'
      path: '/api/v1/calendars'
      fullPath: '/api/v1/calendars'
      preLoaderRoute: typeof ApiV1CalendarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image': {
      id: '/api/public/image'
      path: '/api/public/image'
      fullPath: '/api/public/image'
      preLoaderRoute: typeof ApiPublicImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/e/$eventId': {
      id: '/_authenticated/e/$eventId'
      path: '/e/$eventId'
      fullPath: '/e/$eventId'
      preLoaderRoute: typeof AuthenticatedEEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/events/changes': {
      id: '/api/v1/events/changes'
      path: '/changes'
      fullPath: '/api/v1/events/changes'
      preLoaderRoute: typeof ApiV1EventsChangesRouteImport
      parentRoute: typeof ApiV1EventsRoute
    }
    '/api/v1/events/$canonicalId': {
      id: '/api/v1/events/$canonicalId'
      path: '/$canonicalId'
      fullPath: '/api/v1/events/$canonicalId'
      preLoaderRoute: typeof ApiV1EventsCanonicalIdRouteImport
      parentRoute: typeof ApiV1EventsRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedImportRoute: typeof AuthenticatedImportRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedEEventIdRoute: typeof AuthenticatedEEventIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedImportRoute: AuthenticatedImportRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedEEventIdRoute: AuthenticatedEEventIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiV1EventsRouteChildren {
  ApiV1EventsCanonicalIdRoute: typeof ApiV1EventsCanonicalIdRoute
  ApiV1EventsChangesRoute: typeof ApiV1EventsChangesRoute
}

const ApiV1EventsRouteChildren: ApiV1EventsRouteChildren = {
  ApiV1EventsCanonicalIdRoute: ApiV1EventsCanonicalIdRoute,
  ApiV1EventsChangesRoute: ApiV1EventsChangesRoute,
}

const ApiV1EventsRouteWithChildren = ApiV1EventsRoute._addFileChildren(
  ApiV1EventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  Phase2Route: Phase2Route,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatBadgeRoute: ApiChatBadgeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicImageRoute: ApiPublicImageRoute,
  ApiV1CalendarsRoute: ApiV1CalendarsRoute,
  ApiV1EventsRoute: ApiV1EventsRouteWithChildren,
  ApiV1HealthRoute: ApiV1HealthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
